/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.prokop.app.data.big.test.bigdatatest.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ClientMandatory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5233154590640289737L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClientMandatory\",\"namespace\":\"com.prokop.app.data.big.test.bigdatatest.model\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"active\",\"type\":\"boolean\"},{\"name\":\"gender\",\"type\":{\"type\":\"enum\",\"name\":\"Gender\",\"symbols\":[\"male\",\"female\",\"unknown\"]}},{\"name\":\"last_purchases\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClientMandatory> ENCODER =
      new BinaryMessageEncoder<ClientMandatory>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClientMandatory> DECODER =
      new BinaryMessageDecoder<ClientMandatory>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ClientMandatory> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ClientMandatory> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ClientMandatory> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ClientMandatory>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ClientMandatory to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ClientMandatory from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ClientMandatory instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ClientMandatory fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long id;
   private java.lang.CharSequence name;
   private boolean active;
   private com.prokop.app.data.big.test.bigdatatest.model.Gender gender;
   private java.util.List<java.lang.CharSequence> last_purchases;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClientMandatory() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param active The new value for active
   * @param gender The new value for gender
   * @param last_purchases The new value for last_purchases
   */
  public ClientMandatory(java.lang.Long id, java.lang.CharSequence name, java.lang.Boolean active, com.prokop.app.data.big.test.bigdatatest.model.Gender gender, java.util.List<java.lang.CharSequence> last_purchases) {
    this.id = id;
    this.name = name;
    this.active = active;
    this.gender = gender;
    this.last_purchases = last_purchases;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return active;
    case 3: return gender;
    case 4: return last_purchases;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: active = (java.lang.Boolean)value$; break;
    case 3: gender = (com.prokop.app.data.big.test.bigdatatest.model.Gender)value$; break;
    case 4: last_purchases = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'active' field.
   * @return The value of the 'active' field.
   */
  public boolean getActive() {
    return active;
  }


  /**
   * Sets the value of the 'active' field.
   * @param value the value to set.
   */
  public void setActive(boolean value) {
    this.active = value;
  }

  /**
   * Gets the value of the 'gender' field.
   * @return The value of the 'gender' field.
   */
  public com.prokop.app.data.big.test.bigdatatest.model.Gender getGender() {
    return gender;
  }


  /**
   * Sets the value of the 'gender' field.
   * @param value the value to set.
   */
  public void setGender(com.prokop.app.data.big.test.bigdatatest.model.Gender value) {
    this.gender = value;
  }

  /**
   * Gets the value of the 'last_purchases' field.
   * @return The value of the 'last_purchases' field.
   */
  public java.util.List<java.lang.CharSequence> getLastPurchases() {
    return last_purchases;
  }


  /**
   * Sets the value of the 'last_purchases' field.
   * @param value the value to set.
   */
  public void setLastPurchases(java.util.List<java.lang.CharSequence> value) {
    this.last_purchases = value;
  }

  /**
   * Creates a new ClientMandatory RecordBuilder.
   * @return A new ClientMandatory RecordBuilder
   */
  public static com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder newBuilder() {
    return new com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder();
  }

  /**
   * Creates a new ClientMandatory RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClientMandatory RecordBuilder
   */
  public static com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder newBuilder(com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder other) {
    if (other == null) {
      return new com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder();
    } else {
      return new com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder(other);
    }
  }

  /**
   * Creates a new ClientMandatory RecordBuilder by copying an existing ClientMandatory instance.
   * @param other The existing instance to copy.
   * @return A new ClientMandatory RecordBuilder
   */
  public static com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder newBuilder(com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory other) {
    if (other == null) {
      return new com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder();
    } else {
      return new com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder(other);
    }
  }

  /**
   * RecordBuilder for ClientMandatory instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClientMandatory>
    implements org.apache.avro.data.RecordBuilder<ClientMandatory> {

    private long id;
    private java.lang.CharSequence name;
    private boolean active;
    private com.prokop.app.data.big.test.bigdatatest.model.Gender gender;
    private java.util.List<java.lang.CharSequence> last_purchases;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.active)) {
        this.active = data().deepCopy(fields()[2].schema(), other.active);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.gender)) {
        this.gender = data().deepCopy(fields()[3].schema(), other.gender);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.last_purchases)) {
        this.last_purchases = data().deepCopy(fields()[4].schema(), other.last_purchases);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ClientMandatory instance
     * @param other The existing instance to copy.
     */
    private Builder(com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.active)) {
        this.active = data().deepCopy(fields()[2].schema(), other.active);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.gender)) {
        this.gender = data().deepCopy(fields()[3].schema(), other.gender);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.last_purchases)) {
        this.last_purchases = data().deepCopy(fields()[4].schema(), other.last_purchases);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'active' field.
      * @return The value.
      */
    public boolean getActive() {
      return active;
    }


    /**
      * Sets the value of the 'active' field.
      * @param value The value of 'active'.
      * @return This builder.
      */
    public com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder setActive(boolean value) {
      validate(fields()[2], value);
      this.active = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'active' field has been set.
      * @return True if the 'active' field has been set, false otherwise.
      */
    public boolean hasActive() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'active' field.
      * @return This builder.
      */
    public com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder clearActive() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'gender' field.
      * @return The value.
      */
    public com.prokop.app.data.big.test.bigdatatest.model.Gender getGender() {
      return gender;
    }


    /**
      * Sets the value of the 'gender' field.
      * @param value The value of 'gender'.
      * @return This builder.
      */
    public com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder setGender(com.prokop.app.data.big.test.bigdatatest.model.Gender value) {
      validate(fields()[3], value);
      this.gender = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'gender' field has been set.
      * @return True if the 'gender' field has been set, false otherwise.
      */
    public boolean hasGender() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'gender' field.
      * @return This builder.
      */
    public com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder clearGender() {
      gender = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'last_purchases' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getLastPurchases() {
      return last_purchases;
    }


    /**
      * Sets the value of the 'last_purchases' field.
      * @param value The value of 'last_purchases'.
      * @return This builder.
      */
    public com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder setLastPurchases(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.last_purchases = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'last_purchases' field has been set.
      * @return True if the 'last_purchases' field has been set, false otherwise.
      */
    public boolean hasLastPurchases() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'last_purchases' field.
      * @return This builder.
      */
    public com.prokop.app.data.big.test.bigdatatest.model.ClientMandatory.Builder clearLastPurchases() {
      last_purchases = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClientMandatory build() {
      try {
        ClientMandatory record = new ClientMandatory();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.active = fieldSetFlags()[2] ? this.active : (java.lang.Boolean) defaultValue(fields()[2]);
        record.gender = fieldSetFlags()[3] ? this.gender : (com.prokop.app.data.big.test.bigdatatest.model.Gender) defaultValue(fields()[3]);
        record.last_purchases = fieldSetFlags()[4] ? this.last_purchases : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClientMandatory>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClientMandatory>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClientMandatory>
    READER$ = (org.apache.avro.io.DatumReader<ClientMandatory>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.name);

    out.writeBoolean(this.active);

    out.writeEnum(this.gender.ordinal());

    long size0 = this.last_purchases.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.last_purchases) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.active = in.readBoolean();

      this.gender = com.prokop.app.data.big.test.bigdatatest.model.Gender.values()[in.readEnum()];

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.last_purchases;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("last_purchases").schema());
        this.last_purchases = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.active = in.readBoolean();
          break;

        case 3:
          this.gender = com.prokop.app.data.big.test.bigdatatest.model.Gender.values()[in.readEnum()];
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.last_purchases;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("last_purchases").schema());
            this.last_purchases = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










