/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.prokop.app.data.big.test.bigdatatest.model;
@org.apache.avro.specific.AvroGenerated
public enum Gender implements org.apache.avro.generic.GenericEnumSymbol<Gender> {
  male, female, unknown  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Gender\",\"namespace\":\"com.prokop.app.data.big.test.bigdatatest.model\",\"symbols\":[\"male\",\"female\",\"unknown\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
